### ISSUE TITLE
bettercrypto.org SSL certificate no longer valid

### ISSUE THREAD

**Issue by mephinet** [BetterCrypto/website#2]
Error message when connecting to https://bettercrypto.org/

Websites prove their identity via certificates, which are valid for a set time period. The certificate for bettercrypto.org expired on 3/7/2020.

**Comment by aaronkaplan** [comment]
Hey Philipp,

thanks for noticing. I am looking why the cron job to renew the certificate failed.

It's fixed now.

**Comment by MacLemon** [comment]
Fixed
